### ISSUE TITLE
搞毛?

### ISSUE THREAD

**Issue by Eve-Sama** [xlboy/temp-ts-server-question#1]
![WechatIMG155450](https://user-images.githubusercontent.com/30228406/229763686-42a8806c-4596-4ae4-a38f-73bdac513cdf.png)

**Comment by xlboy** [comment]
https://user-images.githubusercontent.com/63690944/229772268-6bbd6a86-69b1-4aad-b956-c3a909d972f0.mp4

**Comment by Eve-Sama** [comment]
![图片](https://user-images.githubusercontent.com/30228406/230283089-5130acc8-e941-4398-8912-0f302ec316aa.png)

**Comment by Eve-Sama** [comment]
啊哈哈哈哈哈哈 鸡汤来咯
